### ISSUE TITLE
Unknown Field Name

### ISSUE THREAD

**Issue by jaammedia** [bluevisiontec/GoogleShoppingApi#32] opened 2015-03-31 14:12 UTC
When attempting to add a product i get the following notification:
Errors happened while adding products to Google Shopping.
The product "***" hasn't been added to Google Content.
Error calling POST https://www.googleapis.com/content/v2/102686304/products: (400) Unknown field name: age_group
same issue as #24
My Attributes:
![attribute_map](https://cloud.githubusercontent.com/assets/11738093/6920732/4ce3e110-d78e-11e4-894e-df1a67986439.png)

**Comment by schnere** [comment] 2015-03-31 14:25
Did you install the head revision or the latest release/tag? 
This should be fixed in head revision.

**Comment by jaammedia** [comment] 2015-03-31 15:08
latest release

**Comment by jaammedia** [comment] 2015-03-31 19:47
just tried the head revision of the api. throws the exact same error

**Comment by jaammedia** [comment] 2015-04-02 20:03
any idea on how to fix this?

**Comment by schnere** [comment] 2015-04-07 07:20
Hi, I will review this again in the next days...

**Comment by schnere** [comment] 2015-04-07 14:52
I cannot reproduce the error in head revision. I was able to add the attribute and sucessfully upload it to GoogleShopping

**Comment by jaammedia** [comment] 2015-04-07 16:52
Could you please update the Readme.md with your exact steps as I am getting this exact same error every time or either a completely white screen when trying to access the Manage Items from the Google Content API v2 all together. Would also like to note that the white screen is not throwing any error in my logs files.

**Comment by schnere** [comment] 2015-04-15 10:07
When you get a white page you should enable and check php.log .

Please update to newest release (0.2.0) and try again.

**Closed as completed** 2015-06-10 15:36 UTC
Labels: bug

**Comment by jaammedia** [comment] 2015-06-30 17:07
If you don't install Google Content API  via composer then you have to make some changes to how some of the includes are handled.in [magento_root]/vendor/google/apiclient/src/Google/
Just make them match up with your directory structure. Should probably update the https://github.com/bluevisiontec/GoogleShoppingApi#install-manually section of the Readme.md. I can't remember which exact files need changing but the php error log will point you in the right direction.
